apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-b8ng
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0018-tenant/tkrw-pr712-0075-0018-app/devfile-sample-b8ng@sha256:47bd0d3ecf518998d9cf0b6add84965e855367e2b1c4b47167b857b3bc89216c
        name: my-nodejs
        resources: {}
status: {}
